### ISSUE TITLE
Stylus contained malicious code and was removed from the registry by the npm security team

### ISSUE THREAD

**Issue by studds** [mrmckeb/typescript-plugin-css-modules#287]
**Describe the bug**

Can't install as stylus has been removed from npm registry.

**To Reproduce**

1. npm I typescript-plugin-css-modules

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/stylus/-/stylus-0.62.0.tgz - Not found
```

**Expected behavior**

Able to install

**Additional context**

**Comment by pastak** [comment]
I decided to move to [css-modules-kit](https://github.com/mizdra/css-modules-kit) to avoid this.

**Comment by Sansith** [comment]
Effected by this since `typescript-plugin-css-modules` is using `stylus` was removed from the NPM and YARN registries. Pipelines are failing. 

Any workaround for this ?

**Comment by mrmckeb** [comment]
It looks like this might have been a mistake:
https://github.com/stylus/stylus/issues/2938

I'll take a look at this tonight, hopefully in the next 2-3 hours, and try to release a patched version.

In the meantime, you should be able to use your package manager to override the package to the `0.0.1-security` release.
- https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
- https://pnpm.io/package_json#pnpmoverrides
- https://yarnpkg.com/configuration/manifest#resolutions

For example, for pnpm it would be:
```json
{
  "pnpm": {
    "overrides": {
      "stylus": "0.0.1-security",
    }
  }
}
```

Please report back if this does/doesn't help as a workaround.

**Comment by mrmckeb** [comment]
Publishing a small update now, which makes Stylus an optional dependency - meaning that the install will continue if it fails.
https://docs.npmjs.com/cli/v11/configuring-npm/package-json#optionaldependencies

**Comment by mrmckeb** [comment]
[v5.2.0](https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.2.0) is now published.

I've tried to include nothing else in this release apart from two Dependabot security updates.

Please let me know if you hit any issues with this release.

**Comment by edhgoose** [comment]
Thanks for jumping on this so quickly @mrmckeb!

We're still having challenges with Yarn because it looks like it behaves differently to npm. If an optional package fails to install the package will not be installed either.

The relevant docs appear to be:

https://yarnpkg.com/configuration/manifest#optionalDependencies:~:text=Note%20that%20optionalDependencies%20only%20cares%20about%20whether%20the%20package%20should%20install/build%20or%20not%20%2D%20it%20should%20still%20be%20resolvable%2C%20as%20otherwise%20it%27s%20impossible%20to%20tell%20whether%20a%20failure%20to%20retrieve%20the%20package%20metadata%20is%20intentional%20or%20not.

> Note that optionalDependencies only cares about whether the package should install/build or not - it should still be resolvable, as otherwise it's impossible to tell whether a failure to retrieve the package metadata is intentional or not.

**Comment by mrmckeb** [comment]
Thanks @edhgoose, is resolutions a satisfactory workaround for you right now?

I'd like to wait to see what npm does before fully removing Stylus - but if you have no viable workarounds, please let me know ASAP.

**Comment by GuiLec** [comment]
@mrmckeb , I have the same issue as @edhgoose using yarn. It seems yarn behavior with optionalDependencies is different than npm's one...
(Yarn fails to resolve typescript-plugin-css-modules due to 404 on https://registry.yarnpkg.com/stylus/-/stylus-0.62.0.tgz)

<img width="590" height="101" alt="Image" src="https://github.com/user-attachments/assets/50bf2eee-d9e0-4bc0-ba2f-47655f0e8976" />

**Comment by moz-rotimib** [comment]
> [@mrmckeb](https://github.com/mrmckeb) , I have the same issue as [@edhgoose](https://github.com/edhgoose) using yarn. It seems yarn behavior with optionalDependencies is different than npm's one...

Same for me. I'm using yarn and installing this new version doesn't work for me

**Comment by mrmckeb** [comment]
@GuiLec and @moz-rotimib, have you tried using Yarn's resolutions to override the version? See: https://github.com/mrmckeb/typescript-plugin-css-modules/issues/287#issuecomment-3106151162

There are also examples in this thread: https://github.com/stylus/stylus/issues/2938

**Comment by GuiLec** [comment]
Yes adding
```
  "resolutions": {
    "stylus": "0.0.1-security"
  },
```
in my package.json works for me.
Thank you @mrmckeb

**Comment by mrmckeb** [comment]
Thanks for confirming @GuiLec! I'm glad that everyone has either a fix or a workaround for now 🎉 

It's late here (Australia 🇦🇺), but we'll see what happens with Stylus overnight.

If this is still an issue in my morning, I'll create a major release to remove Stylus.

**Comment by moz-rotimib** [comment]
> Yes adding
> 
> ```
>   "resolutions": {
>     "stylus": "0.0.1-security"
>   },
> ```
> 
> in my package.json works for me. Thank you [@mrmckeb](https://github.com/mrmckeb)

Unfortunately doing this doesn't work for me. I get this error.

```
error Couldn't find any versions for "stylus" that matches "^0.62.0"
```

**Comment by dariuszpaluch** [comment]
Yup for `yarn` only resolutions approach is working, but making the library optional is failing.

> > Yes adding
> > ```
> >   "resolutions": {
> >     "stylus": "0.0.1-security"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in my package.json works for me. Thank you [@mrmckeb](https://github.com/mrmckeb)
> 
> Unfortunately doing this doesn't work for me. I get this error.
> 
> ```
> error Couldn't find any versions for "stylus" that matches "^0.62.0"
> ```

Check yarn lock, 
should looks like 

```
  stylus@0.0.1-security, stylus@^0.62.0:
  version "0.0.1-security"
  resolved "..."
  integrity "..."

**Comment by mrmckeb** [comment]
@moz-rotimib Can you share your package.json, or more info?

For Yarn 1.x-4.x, it should be:
```json
{
  "name": "your-project",
  "devDependencies": {
    "typescript-plugin-css-modules": "^5.2.0"
  },
  "resolutions": {
    "stylus": "0.0.1-security"
  }
}
```

I don't use Yarn myself, but the docs on resolutions are here:
- 1.x: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
- 2.x-4.x: https://yarnpkg.com/configuration/manifest#resolutions

You should also be able to target this package directly with `"typescript-plugin-css-modules/stylus": "0.0.1-security"`.

The Stylus maintainer has also shared more detailed instructions here (scroll down and you'll find Yarn instructions): https://github.com/stylus/stylus/issues/2938#issue-3254793141

**Comment by mrmckeb** [comment]
Thanks for confirming @dariuszpaluch!

**Comment by moz-rotimib** [comment]
This is my [package.json](https://github.com/user-attachments/files/21388340/package.json)

I deleted my yarn.lock before running `yarn` but I still get this issue. I'm using yarn v1.22.22

**Comment by mrmckeb** [comment]
I think I found your issue @moz-rotimib. In a monorepo, resolutions needs to be set in the root `package.json`:
https://github.com/common-voice/common-voice/blob/main/package.json

You can see some other packages in `"resolutions"` in that file already. Try adding it there and let us know if you're still having trouble 😊

You're updating the `package.json` file in a package, which won't work:
https://github.com/common-voice/common-voice/blob/main/web/package.json

You might also want to leave it at 3.4.0 for now, but looking at your project quickly, I think 5.2.0 should be OK as well.

**Comment by moz-rotimib** [comment]
Yes that was the solution! @mrmckeb thank you soo much for your assistance. It's late for you and I appreciate you helping me to fix it. Thanks

**Comment by mrmckeb** [comment]
GitHub/npm are restoring Stylus. This was a false positive, so you should be able to remove your resolutions in a few hours.

Again, see the Stylus thread for more: https://github.com/stylus/stylus/issues/2938#issue-3254793141

**Comment by sayemafatema** [comment]
By when can we expect a fix? My project is not running with any of the solutions provided above.

**Comment by jensluch** [comment]
> By when can we expect a fix? My project is not running with any of the solutions provided above.

Seems like everything works fine now, yarn runs and the project builds without issues.

**Comment by vance** [comment]
Confirmed with other developer, nuke node_modules/clean cache/delete lockfile... yarn berry is still failing, and the `overrides` workaround does not work. Maybe because it's a major version bump and not in range, or something to do with it being optional? Is it possible to bump `typescript-plugin-css-modules` to use `stylus` version post-snafu?
